version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=movie_review_project.settings
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=pyamqp://guest:guest@rabbitmq:5672//
      # Add other environment variables if needed

  rabbitmq:
    image: rabbitmq:latest

  celery:
    build: .
    command: celery -A movie_review_project worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=movie_review_project.settings
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=pyamqp://guest:guest@rabbitmq:5672//
      # Add other environment variables if needed

networks:
  default:
    external:
      name: mynetwork  # Use an existing network or create a new one

volumes:
  myvolume:
